name: Notificaci贸n Hola Mundo

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el c贸digo
        uses: actions/checkout@v4

      - name: Ejecutar Hola Mundo
        run: node index.js

      - name: Enviar notificaci贸n a ntfy
        run: |
          curl -X POST \
          -H "Title: GitHub Actions " \
          -H "Priority: 3" \
          -H "Tags: devops,github" \
          -d "Se subi贸 c贸digo a la rama main del repositorio." \
          https://ntfy.sh/devops-itla
